"use client"

import { motion } from "framer-motion"
import { Play, TrendingUp, RefreshCw, Target } from "lucide-react"
import { Button } from "@/components/ui/button"
import Image from "next/image"

export default function CreativeSolutionsPage() {
  const stats = [
    {
      percentage: "65%",
      description:
        "Top performing companies (in terms of online presence) had a well-crafted content marketing strategy in place.",
    },
    {
      percentage: "72%",
      description: "Marketers worldwide said relevant content creation was the most effective SEO tactic.",
    },
    {
      percentage: "52%",
      description:
        "Website users/visitors are less likely to return to a website if they have had a poor experience the first time.",
    },
    {
      percentage: "3x",
      description:
        "More leads are generated by content marketing at 60% less marketing spend compared with traditional marketing.",
    },
  ]

  const services = [
    {
      icon: <Play className="w-8 h-8" />,
      title: "TVC & OVC",
      description:
        "Crafting memorable narratives, our TVC & OVC service produces compelling commercials and online videos, delivering captivating brand stories to diverse audiences.",
    },
    {
      icon: <Target className="w-8 h-8" />,
      title: "Graphics Design",
      description:
        "Transforming ideas into captivating visuals, our graphics design service crafts compelling brand imagery, ensuring impactful storytelling and visual appeal.",
    },
    {
      icon: <RefreshCw className="w-8 h-8" />,
      title: "Motion graphics",
      description:
        "Breathing life into visuals, our motion design service creates dynamic and engaging animations, amplifying brand messages with captivating movement.",
    },
    {
      icon: <TrendingUp className="w-8 h-8" />,
      title: "Video Editing",
      description:
        "Refining raw footage into seamless stories, our video editing service expertly crafts compelling narratives, ensuring polished and engaging visual storytelling.",
    },
  ]

  const designSamples = [
    "/social-media-post.png",
    "/brand-poster-design.jpg",
    "/modern-product-display.png",
    "/modern-business-card.png",
    "/flyer-design.png",
    "/instagram-post-template.png",
  ]

  return (
    <div className="min-h-screen bg-background">


      {/* Hero Section */}
      <section className="relative min-h-screen flex items-center overflow-hidden pt-32 pb-20">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            {/* Left Content */}
            <motion.div
              initial={{ opacity: 0, x: -50 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8 }}
              className="order-2 lg:order-1"
            >
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-foreground mb-6 leading-tight">
                Strategic <span className="text-primary">TVC & OVC</span>
                <br />
                Innovations for Your Brand
              </h1>
              <p className="text-muted-foreground text-lg mb-8 max-w-xl text-justify">
                TVC & OVC services blend captivating visuals and storytelling techniques to create compelling brand
                narratives across television and online platforms. These offerings aim to enhance brand visibility,
                engage audiences, and leave a lasting impact in today's diverse media landscape.
              </p>
              <Button size="lg" className="bg-primary hover:bg-primary/90 text-white rounded-full px-8 py-6 text-lg">
                <Play className="w-5 h-5 mr-2 fill-white" />
                Watch Showreel
              </Button>
            </motion.div>

            {/* Right Image - Colorful 3D Shape */}
            <motion.div
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              className="order-1 lg:order-2 relative"
            >
              <div className="relative w-full aspect-square max-w-2xl mx-auto">
                <Image
                  src="/abstract-3d-colorful-gradient-shape-pink-purple-re.jpg"
                  alt="Creative 3D Design"
                  width={600}
                  height={600}
                  className="w-full h-full object-contain animate-float"
                />
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Graphics Design Showcase Section */}
      <section className="py-20 bg-muted/30">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            {/* Left - Design Samples Grid */}
            <motion.div
              initial={{ opacity: 0, x: -50 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8 }}
              viewport={{ once: true }}
              className="relative"
            >
              <div className="grid grid-cols-2 gap-4">
                {designSamples.map((sample, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, scale: 0.8 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.5, delay: index * 0.1 }}
                    viewport={{ once: true }}
                    className="relative group cursor-pointer"
                  >
                    <div className="relative aspect-square overflow-hidden rounded-lg border border-border bg-card">
                      <Image
                        src={sample || "/placeholder.svg"}
                        alt={`Design Sample ${index + 1}`}
                        width={300}
                        height={300}
                        className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110"
                      />
                    </div>
                  </motion.div>
                ))}
              </div>
              {/* Decorative circles */}
              <div className="absolute -top-4 -left-4 w-12 h-12 rounded-full bg-primary/20 animate-pulse" />
              <div className="absolute -bottom-4 -right-4 w-16 h-16 rounded-full bg-primary/30 animate-pulse" />
            </motion.div>

            {/* Right - Content */}
            <motion.div
              initial={{ opacity: 0, x: 50 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8 }}
              viewport={{ once: true }}
            >
              <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-foreground mb-6">
                Crafting Creativity: Your Gateway to Exceptional <span className="text-primary">Graphics Design</span>
              </h2>
              <p className="text-muted-foreground text-lg mb-6 text-justify">
                Immerse your audience in a world of captivating storytelling with our bespoke motion graphics.
              </p>
              <p className="text-muted-foreground text-lg text-justify">
                At IMBD Agency, we specialize in crafting dynamic visual narratives that breathe life into concepts.
                Through innovative animation, vibrant designs, and precise synchronization, we create compelling stories
                that resonate. Our team's passion for pushing creative boundaries ensures each frame is meticulously
                crafted to convey your message memorably. Elevate your brand, presentations, or social media content
                with our tailored motion graphic solutions, leaving an indelible mark on your audience.
              </p>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Motion Graphics Section */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="max-w-4xl"
          >
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-foreground mb-6">
              Unleashing Creativity Frame by Frame With <span className="text-primary">Motion Graphics</span>
            </h2>
            <p className="text-muted-foreground text-lg mb-6 text-justify">
              Immerse your audience in a world of captivating storytelling with our bespoke motion graphics.
            </p>
            <p className="text-muted-foreground text-lg text-justify">
              At IMBD Agency, we specialize in crafting dynamic visual narratives that breathe life into concepts.
              Through innovative animation, vibrant designs, and precise synchronization, we create compelling stories
              that resonate. Our team's passion for pushing creative boundaries ensures each frame is meticulously
              crafted to convey your message memorably. Elevate your brand, presentations, or social media content with
              our tailored motion graphic solutions, leaving an indelible mark on your audience.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Statistics Section */}
      <section className="py-20 bg-muted/30">
        <div className="container mx-auto px-4">
          <motion.h2
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-3xl md:text-4xl lg:text-5xl font-bold text-center text-foreground mb-16"
          >
            Why Does <span className="text-primary underline decoration-primary">Content Marketing</span> Matter?
          </motion.h2>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {stats.map((stat, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="bg-card border border-border rounded-lg p-8 hover:border-primary transition-colors duration-300"
              >
                <h3 className="text-5xl md:text-6xl font-bold text-primary mb-4">{stat.percentage}</h3>
                <p className="text-muted-foreground text-sm leading-relaxed text-justify">{stat.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Creative Solutions Services */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <motion.h2
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-3xl md:text-4xl lg:text-5xl font-bold text-center text-foreground mb-16"
          >
            <span className="text-primary">Creative Solutions</span> We Provide
          </motion.h2>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {services.map((service, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="bg-card border border-border rounded-lg p-8 hover:border-primary transition-all duration-300 group"
              >
                <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mb-6 mx-auto group-hover:bg-primary/20 transition-colors">
                  <div className="text-primary">{service.icon}</div>
                </div>
                <h3 className="text-xl font-bold text-foreground mb-4 text-center">{service.title}</h3>
                <p className="text-muted-foreground text-sm leading-relaxed text-justify">{service.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-muted/30">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="text-center max-w-3xl mx-auto"
          >
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-foreground mb-6">
              Ready to Elevate Your <span className="text-primary">Creative Content?</span>
            </h2>
            <p className="text-muted-foreground text-lg mb-8">
              Let's collaborate to bring your vision to life with compelling visuals and engaging storytelling.
            </p>
            <Button size="lg" className="bg-primary hover:bg-primary/90 text-white rounded-full px-8 py-6 text-lg">
              Start Your Project
            </Button>
          </motion.div>
        </div>
      </section>

    </div>
  )
}
